### ISSUE TITLE
MSI: Fix td-agent.conf default configuration path

### ISSUE THREAD

**Issue by kenhys** [fluent-plugins-nursery/td-agent-builder#120]
# Problem

Default configuration file contains inappropriate path.

# Expected

Fixed path by default

# Actual

For example, `/var/log/td-agent/td` exists.

```
# This section matches events whose tag is td.DATABASE.TABLE
<match td.*.*>
  @type tdlog
  @id output_td
  apikey YOUR_API_KEY

  auto_create_table
  <buffer>
    @type file
    path /var/log/td-agent/buffer/td
  </buffer>
```

**Comment by kenhys** [comment]
By default, there is no appropriate Action to rewrite file.

**Comment by kenhys** [comment]
New extension is required?
https://wixtoolset.org/documentation/manual/v3/wixdev/extensions/

**Comment by kenhys** [comment]
It seems another choise: JScriptCall.

**Comment by kenhys** [comment]
I'm investigating jscript case: https://github.com/kenhys/wixtoolset-examples/tree/master/jscript

**Comment by ashie** [comment]
You can use Ruby code in the config file: https://docs.fluentd.org/configuration/config-file#embedded-ruby-code
I think getting the path from an environment variable is proper way in this case.

**Comment by kenhys** [comment]
Fixed by https://github.com/fluent-plugins-nursery/td-agent-builder/pull/131
