### ISSUE TITLE
Migrate Gemfile based gem installation

### ISSUE THREAD

**Issue by cosmo0920** [fluent-plugins-nursery/td-agent-builder#126]
Currently, gem installation is proceeded by `gem install` and these files:
https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/td-agent/core_gems.rb
https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/td-agent/plugin_gems.rb

Recent rubygems can handle Gemfile with `gem install --file`:
https://github.com/rubygems/rubygems/blob/6d167c1df771c7ef3f2f7c4fb12c4416c0a384b6/lib/rubygems/install_update_options.rb#L136-L151

Using `gem install --file Gemfile` is one of the way to migrate Gemfile based installation.

**Comment by kenhys** [comment]
Working on https://github.com/fluent-plugins-nursery/td-agent-builder/pull/142
