### ISSUE TITLE
Enhancement: Publish a Gemfile.lock with each td-agent release.

### ISSUE THREAD

**Issue by Houlistonm** [fluent-plugins-nursery/td-agent-builder#128]
td-agent vX.Y.Z represents a curated collection of GEMs that have been tested prior to their release.

Our project needs to add some additional plugins to support our requirements with out invalidating the integrity of the release. 
Our CI pipeline takes the release, constructs a Gemfile.lock and then tries to install additional GEMS using td-agent-gem to ensure we don't replace any embedded/tested GEMS.

It is desirable if td-agent could create the lock file and publish it with the release.

**Comment by cosmo0920** [comment]
Currently, td-agent-builder building system does not use Gemfile and Gemfile.lock:
https://github.com/fluent-plugins-nursery/td-agent-builder/issues/126

Now, we use https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/td-agent/core_gems.rb and https://github.com/fluent-plugins-nursery/td-agent-builder/blob/master/td-agent/plugin_gems.rb for bundling gems.

**Comment by Houlistonm** [comment]
Thank you for the feedback.
Does your builder allow users to safely add gems to their environment as we're attempting to do with the Gemfile.lock?

**Comment by cosmo0920** [comment]
We'd completed the first step to achieve this: #142.

**Comment by cosmo0920** [comment]
We'd already published Gemfile.lock on td-agent 4.0.1 release.

**Comment by ashie** [comment]
Reopened, because probably users want bundled Gemfile.lock, but we don't yet add it to the package.
