### ISSUE TITLE
CI: Need activesupport 6.1 to back to normal AArch64 package building on Travis-CI

### ISSUE THREAD

**Issue by kenhys** [fluent-plugins-nursery/td-agent-builder#153]
# Problem

Because of gem dependency, td-agent requires tzinfo 2.x but , travis gem requires tzinfo 1.x.
As a result, CI can't work as expected.

# Expected

CI on Travis works as expected.

# Actual

CI on Travis always fails.

# Action

We need to wait until activesupport 6.1 release.

Automultiplatform again
https://github.com/rubygems/bundler/pull/7580

was merged, it will be shipped as 6.1.0. we wait https://github.com/rails/rails/milestone/69 6.1.0 milestone.

**Comment by ashie** [comment]
#232 We'll move back CI for AArch64 to GitHub Actions
