### ISSUE TITLE
Windows: TD_AGENT_TOPDIR is not applied correctly

### ISSUE THREAD

**Issue by kenhys** [fluent-plugins-nursery/td-agent-builder#155]
# Problem

On Windows, c:/var/log/td-agent/buffer/fd is created

# Expected

c:/opt/td-agent/var/log/td-agent/buffer/td is used

# Action

We need to update td-agent.conf.tmpl.

**Comment by kenhys** [comment]
Here is the actual td-agent.log.

```
2020-08-04 10:10:56 +0900 [info]: starting fluentd-1.11.1 pid=1536 ruby="2.7.1"
2020-08-04 10:10:56 +0900 [info]: spawn command to main:  cmdline=["C:/opt/td-agent/bin/ruby.exe", "-Eascii-8bit:ascii-8bit", "C:/opt/td-agent/bin/fluentd", "-c", "C:\\opt\\td-agent\\\\etc\\td-agent\\td-agent.conf", "-o", "C:\\opt\\td-agent\\\\td-agent.log", "-x", "fluentdwinsvc", "--under-supervisor"]
2020-08-04 10:11:00 +0900 [info]: adding match pattern="td.*.*" type="tdlog"
```

**Comment by kenhys** [comment]
So, if in td-agent.conf use `ENV['TD_AGENT_TOPDIR']` still /var/log/ is created.

**Comment by kenhys** [comment]
Currently use fluentd.rb to register, so winsvc.rb is used to control. it use always rubybin_dir/fluentd in `service_main_start`.

**Comment by kenhys** [comment]
1. force to use fluentd.bat
    need to fork winsvc.rb?
2. set TD_AGENT_TOPDIR explicitly and use TD_AGENT_TOPDIR
3. rewrite fluentd.conf and embed full path.

**Comment by kenhys** [comment]
2. use https://wixtoolset.org/documentation/manual/v3/xsd/wix/environment.html

**Comment by kenhys** [comment]
It must be put under Component.

**Comment by kenhys** [comment]
Now building fixed version.

**Comment by cosmo0920** [comment]
https://github.com/fluent-plugins-nursery/td-agent-builder/pull/162 is merged. Closing,

**Comment by daipom** [comment]
https://github.com/fluent/fluent-package-builder/pull/162#issuecomment-1645187638

This will be fixed completely by

* #521
