### ISSUE TITLE
Integrate Gemfile and Gemfile.lock under gemfiles/

### ISSUE THREAD

**Issue by kenhys** [fluent-plugins-nursery/td-agent-builder#158]
# Probrem

We need Gemfile integration for simplicity

# Expected

maintain Single Gemfile and Gemfile.lock for simplicity

# Actual

There are two Gemfile depend on environment.

gemfiles/linux/Gemfile
gemfile/windows/Gemfile

# Action

After bundler 2.2.0 is released, auto multiplatform is enabled, so we can start to integrate Gemfile.

* Automultiplatform again https://github.com/rubygems/bundler/pull/7580

**Comment by kenhys** [comment]
FYI: https://rubygems.org/gems/bundler/versions/2.2.0.rc.1

**Comment by ashie** [comment]
If we achieve this work, I want move Gemfile.lock to the same directory with config.rb and avoid rewriting it (which is introduced at #189).
