### ISSUE TITLE
Write down more installation testcases

### ISSUE THREAD

**Issue by cosmo0920** [fluent-plugins-nursery/td-agent-builder#163]
Currently, installation testcases should execute package installation only.
We should do more installation testcases. 
e.g) [Serverspec](https://serverspec.org/resource_types.html).

**Comment by kenhys** [comment]
Test linux or windows specific bundled gems.

**Comment by kenhys** [comment]
On linux side, https://github.com/fluent-plugins-nursery/td-agent-builder/pull/174 will cover it.
So, I'll try to add windows too.

**Comment by kenhys** [comment]
bundled for windows packages:

```
win32-event -> win32-ipc -> ffi
win32-service -> ffi, ffi-win32-extensions
windows-pr -> win32-api, windows-api
winevt_c
fluent-plugin-parser-winevt_xml
fluent-plugin-windows-eventlog" -> win32-eventlog -> ffi
```

**Comment by kenhys** [comment]
I'll work windows test case on https://github.com/fluent-plugins-nursery/td-agent-builder/pull/180

**Comment by cosmo0920** [comment]
Windows and Linux installation testcases are merged into master.
We can close this issue.
