### ISSUE TITLE
deb: don't use apt-key in install steps

### ISSUE THREAD

**Issue by kenhys** [fluent-plugins-nursery/td-agent-builder#168]
# Problem

https://docs.fluentd.org/installation/install-by-deb install steps depends on deprecated apt-key.
apt-key will be removed Debian 11(bullseye) or later.

# Expected

provide keyring package and use it.

# Actual

https://docs.fluentd.org/installation/install-by-deb uses apt-key

**Comment by kenhys** [comment]
TODO: add task to create td-agent-apt-source packages

**Comment by kenhys** [comment]
https://github.com/fluent-plugins-nursery/td-agent-builder/pull/181 will fix it.

**Comment by cosmo0920** [comment]
https://github.com/fluent-plugins-nursery/td-agent-builder/pull/182 will also fix this issue.

**Comment by kenhys** [comment]
I'll add test case for apt-source.

**Comment by kenhys** [comment]
Fixed by https://github.com/fluent-plugins-nursery/td-agent-builder/pull/183
