### ISSUE TITLE
Question: Should we use different UpgradeCode for td-agent4?

### ISSUE THREAD

**Issue by cosmo0920** [fluent-plugins-nursery/td-agent-builder#17]
Currently, we use the same UpgradeCode for MSI package.

* td-agent-builder: https://github.com/clear-code/td-agent-builder/blob/d55bc8e1dbcd705e440c7b9547fdf792fefad995/td-agent/msi/parameters.wxi.erb#L5
* omnibus-td-agent: https://github.com/treasure-data/omnibus-td-agent/blob/master/config/projects/td-agent3.rb#L60

This should be valid but td-agent 3 and 4 will not be incomplatible due to upgrading Ruby version and such incompatible changes.

How do we treat it?

**Comment by kenhys** [comment]
working on https://github.com/fluent-plugins-nursery/td-agent-builder/pull/119

**Comment by ashie** [comment]
I disagree to change `UpgradeCode`.
If we change it, both td-agent3 and td-agent4 can exist in the same system, but we wouldn't guarantee such situation.

**Comment by kenhys** [comment]
I've closed #119 and it seems that there is no strong need to change `UpgradeCode`.
I'll close this issue.
