### ISSUE TITLE
Repair AArch64 package building on Travis CI

### ISSUE THREAD

**Issue by cosmo0920** [fluent-plugins-nursery/td-agent-builder#175]
Currently, our CI is broken for building aarch64 packages.
This is because tzdata version requirements mismatch:
https://travis-ci.com/github/fluent-plugins-nursery/td-agent-builder/jobs/367744595#L120

**Comment by ashie** [comment]
Dup of #153 ?

**Comment by cosmo0920** [comment]
Oh, I’d overlooked. thanks!
