### ISSUE TITLE
Failed to start td-agent with aarch64

### ISSUE THREAD

**Issue by rluisr** [fluent-plugins-nursery/td-agent-builder#176]
Summary
========
Failed to start td-agent **4.0.0** on CentOS 8 and 7.

```
# cat /var/log/messages

Aug 13 18:18:00 ip-10-105-44-194 fluentd[15556]: <jemalloc>: Unsupported system page size
Aug 13 18:18:00 ip-10-105-44-194 fluentd[15556]: <jemalloc>: Unsupported system page size
Aug 13 18:18:00 ip-10-105-44-194 fluentd[15556]: [FATAL] failed to allocate memory
```

Reproduce
=========
```
# yum install http://packages.treasuredata.com.s3.amazonaws.com/4/redhat/8/aarch64/td-agent-4.0.0-1.el8.aarch64.rpm -y
# systemctl start td-agent
```

Environnment
===========
- CentOS Linux release 8.2.2004 (Core)
- aarch64
- AWS EC2 ARM instance (M6g)

Please let me know if any of this information is missing, as I may be missing some of it.

**Comment by kenhys** [comment]
@rluisr it may be that jemalloc is not compiled appropriately on aarch64 (not sure yet).

As a workaround, 
just comment out `#Environment=LD_PRELOAD=/opt/td-agent/lib/libjemalloc.so` in `td-agent.servce` then execute systemctl daemon-reload && systemctl start td-agent works as expected. (even though jemalloc can't be enabled :sob: )

```
$ cat /lib/systemd/system/td-agent.service 
[Unit]
Description=td-agent: Fluentd based data collector for Treasure Data
Documentation=https://docs.treasuredata.com/articles/td-agent
After=network-online.target
Wants=network-online.target

[Service]
User=td-agent
Group=td-agent
LimitNOFILE=65536
#Environment=LD_PRELOAD=/opt/td-agent/lib/libjemalloc.so
Environment=GEM_HOME=/opt/td-agent/lib/ruby/gems/2.7.0/
Environment=GEM_PATH=/opt/td-agent/lib/ruby/gems/2.7.0/
Environment=FLUENT_CONF=/etc/td-agent/td-agent.conf
Environment=FLUENT_PLUGIN=/etc/td-agent/plugin
Environment=FLUENT_SOCKET=/var/run/td-agent/td-agent.sock
Environment=TD_AGENT_LOG_FILE=/var/log/td-agent/td-agent.log
Environment=TD_AGENT_OPTIONS=
EnvironmentFile=-/etc/sysconfig/td-agent
PIDFile=/var/run/td-agent/td-agent.pid
RuntimeDirectory=td-agent
Type=forking
# XXX: Fix fluentd executables path
ExecStart=/opt/td-agent/bin/fluentd --log $TD_AGENT_LOG_FILE --daemon /var/run/td-agent/td-agent.pid $TD_AGENT_OPTIONS
ExecStop=/bin/kill -TERM ${MAINPID}
ExecReload=/bin/kill -HUP ${MAINPID}
Restart=always
TimeoutStopSec=120

[Install]
WantedBy=multi-user.target
```

**Comment by repeatedly** [comment]
I confirmed no problem on amazon linux 2 and ubuntu bionic.
I'm now trying to check centos 8 with non-AWS environment.

**Comment by rluisr** [comment]
@kenhys working perfectly! thanks!

@repeatedly perhaps, AL2 is important?

**Comment by repeatedly** [comment]
> AL2 is important?

Yes.

The problem is different PAGE_SIZE on Arm64 with CentOS. 
Arm64 with Ubuntu/AL2 and x86_64 with all OSes use 4096 page size but Arm64 with CentOS uses 65536 page size.

**Comment by kenhys** [comment]
FYI: --with-lg-page configure option may be able to control page size when building jemalloc

**Comment by repeatedly** [comment]
Easy to add its option to only Arm64 RPM package?

**Comment by kenhys** [comment]
@repeatedly I'll check it.

**Comment by ashie** [comment]
The cause is that the difference of the kernel between build time vs run time.
When the package is built using qemu:

```
 `rake yum:build YUM_TARGETS=centos-8-aarch64`
```

non-default kernel is used:

```
$ uname -a
Linux 5b7a1d11123f 5.4.0-42-generic #46-Ubuntu SMP Fri Jul 10 00:24:02 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
$ getconf PAGESIZE
4096
```

> FYI: --with-lg-page configure option may be able to control page size when building jemalloc

It should fix this issue.

refs:
* https://github.com/jemalloc/jemalloc/issues/467
* https://github.com/jemalloc/jemalloc/pull/769
