### ISSUE TITLE
td-agent.conf  remains intact to original after the rpm package is made

### ISSUE THREAD

**Issue by subash20** [fluent-plugins-nursery/td-agent-builder#179]
I change the td-agent.conf configuration file as per my requirement and made the rpm package. But the configuration files remains the original  as I had clone at first.  I change configuration file at td-agent-builder/td-agent/templates/etc/td-agent/td-agent.conf
and td-agent-builder/td-agent/templates/opt/td-agent/share/td-agent.conf.tmpl. Any solution ??

**Comment by cosmo0920** [comment]
This building system requires "git commit" to reflect changes into built package.
This is because creating tarball for packaging depends on `git archive`.
If you want to change file contents and package them, please use `git commit` to save their contents.

**Comment by kenhys** [comment]
@subash20 
I think https://github.com/fluent-plugins-nursery/td-agent-builder/issues/179#issuecomment-677461543 will help you to solve this issue.

So, I'll close this issue. If you have another question, please open a new issue.
