### ISSUE TITLE
MSI: Register/Unregister td-agent service by the installer

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#18]
Currently it requires to register/unregister manually:
https://docs.fluentd.org/installation/install-by-msi#step-4-run-td-agent-as-windows-service

**Comment by ashie** [comment]
See also: https://github.com/treasure-data/omnibus-td-agent/issues/246

**Comment by nmaludy** [comment]
+1 for this

**Comment by kenhys** [comment]
It was fixed by https://github.com/fluent-plugins-nursery/td-agent-builder/pull/122

**Comment by kenhys** [comment]
T.B.D.
1.11.0 is not support `--reg-winsvc-delay-start` yet, so `--reg-winsvc-auto-start --reg-winsvc-delay-start` is not applied.

**Comment by kenhys** [comment]
#122 was merged.
