### ISSUE TITLE
Support to show both of td-agent version and fluentd version at the same time

### ISSUE THREAD

**Issue by kenhys** [fluent-plugins-nursery/td-agent-builder#224]
# Problem

td-agent shows fluentd version, it doesn't match td-agent itself.
(In issue tracker, most of the reporters doesn't write both of them.)

# Actual

td-agent shows only fluentd version

# Expected

td-agent shows td-agent version and fluentd version at the same time.

**Comment by kenhys** [comment]
related files:

./td-agent/msi/assets/td-agent.bat
./opt/td-agent/share/config.rb
fluent/version.rb

**Comment by kenhys** [comment]
Expected result:

```
 /usr/sbin/td-agent --version
td-agent 4.0.1 fluentd 1.11.2 (2f80f6cf0a4aa44b9795cd6a66894a6b8fa70d06)
```

**Comment by cosmo0920** [comment]
https://github.com/fluent-plugins-nursery/td-agent-builder/pull/226 should fix this.
Closing.
