### ISSUE TITLE
Installing specific version of td-agent using yum

### ISSUE THREAD

**Issue by eredi93** [fluent-plugins-nursery/td-agent-builder#229]
👋  Hi there,

I need to modify the systemd file for td-agent and add a `Before` to the `Unit` section. to avoid using `sed` which could screw with the config. I'm planning on replacing the systemd file completely.
I noticed:
https://github.com/fluent-plugins-nursery/td-agent-builder/blob/2bd736db4722ce3cf552877ec11ecb09dd313d6d/td-agent/templates/etc/systemd/td-agent.service.erb#L26

Which makes me think the path might change at some point making my vendored file out of date.
I noticed that the only yum package version available via tresure-data repo is `td-agent.x86_64`.

```
$ sudo yum search td-agent
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
197 packages excluded due to repository priority protections
================================================================== N/S matched: td-agent ===================================================================
td-agent.x86_64 : The stable distribution of Fluentd

  Name and summary matches only, use "search all" for everything.
```

AFAIK there is no way for me to installed a specific version. We install td-agent using ansible + yum when generating our AMIs and it looks like that https://docs.ansible.com/ansible/latest/collections/ansible/builtin/yum_module.html requires the version in the name. 

Could you make the package available under something like `td-agent-4.0.1-0.amazon2.x86_64`?
I believe that should allow me to pin to a version instead of installing latest every time we build a new AMI.

Thanks 🙇

**Comment by kenhys** [comment]
@eredi93 

It seems that you can install specific version of td-agent by:

```
$ sudo yum install td-agent-4.0.1-1.amzn2
```

**Comment by eredi93** [comment]
it worked! 
TIL https://td-agent-package-browser.herokuapp.com/4/amazon/2/x86_64

Thanks 💯
