### ISSUE TITLE
Support Ruby 3.0

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#249]
At least https://github.com/socketry/protocol-http2/issues/6 prevents it.

**Comment by ashie** [comment]
https://github.com/fluent-plugins-nursery/td-agent-builder/blob/3f36cc012c3b4c66dd4fb20bcf668de446772310/td-agent/Gemfile#L25-L27

**Comment by ashie** [comment]
> It causes install error on Windows:

It's released gem's issue.
It doesn't occur when I build protocol-http2-0.14.1 by myself and use it.

**Comment by ashie** [comment]
> It's released gem's issue.
> It doesn't occur when I build protocol-http2-0.14.1 by myself and use it.

The fixed version (0.14.2) has been released: https://rubygems.org/gems/protocol-http2/versions/0.14.2
Now we can remove the workaround:
https://github.com/fluent-plugins-nursery/td-agent-builder/blob/3f36cc012c3b4c66dd4fb20bcf668de446772310/td-agent/Rakefile#L899-L904

**Comment by ashie** [comment]
> Now we can remove the workaround:

Done: #251, #252

And I've added Ruby 3.0 sources: https://github.com/fluent-plugins-nursery/td-agent-builder/commit/20814bcc55dc4f9d1d3c2060f517457b6150a9f2

Remaining issue is msgpack: https://rubygems.org/gems/msgpack/versions/1.3.3-x86-mingw32

**Comment by ashie** [comment]
> Remaining issue is msgpack's fat gem: https://rubygems.org/gems/msgpack/versions/1.3.3-x86-mingw32

msgpack 1.4.0 has been released which stops releasing fat gem: https://rubygems.org/gems/msgpack/versions/1.4.0

Next blocker is nokogiri:
```
nokogiri-1.10.10-x64-mingw32 requires ruby version >= 2.3, < 2.8.dev, which is
incompatible with the current version, ruby 3.0.0p0
```

**Comment by ashie** [comment]
> Next blocker is nokogiri:

#253 fixes this issue.
Now I can build td-agent with Ruby 3.0 but I got the following error on run time:

```
<internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require': cannot load such file -- webrick (LoadError)
	from <internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/td-agent/lib/ruby/gems/3.0.0/gems/fluentd-1.12.0/lib/fluent/rpc.rb:17:in `<top (required)>'
	from <internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/td-agent/lib/ruby/gems/3.0.0/gems/fluentd-1.12.0/lib/fluent/supervisor.rb:27:in `<top (required)>'
	from <internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/td-agent/lib/ruby/gems/3.0.0/gems/fluentd-1.12.0/lib/fluent/command/fluentd.rb:19:in `<top (required)>'
	from <internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/opt/td-agent/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from /opt/td-agent/lib/ruby/gems/3.0.0/gems/fluentd-1.12.0/bin/fluentd:8:in `<top (required)>'
	from /opt/td-agent/bin/fluentd:23:in `load'
	from /opt/td-agent/bin/fluentd:23:in `<top (required)>'
	from /usr/sbin/td-agent:15:in `load'
	from /usr/sbin/td-agent:15:in `<main>'
```

because Ruby 3.0 drops webrick from bundled gems.

**Comment by kenhys** [comment]
The last blocker will be fixed by https://github.com/fluent-plugins-nursery/td-agent-builder/pull/265

**Comment by ashie** [comment]
I'll open new issue if remaining issues are found.
