### ISSUE TITLE
fluentd is still installed not only by `bundle install` but also `gem install`

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#263]
By #261, most gems are installed by `bundle install` but fluentd is still installed by `gem install`.
When we replace it with bundler, `bundle exec` is required to launch fluentd because installed path is different from other gems due to using git source instead of rubygems.

**Comment by kenhys** [comment]
For example, you can check it by dpkg-deb -c .deb.

* ./opt/td-agent/lib/ruby/gems/2.7.0/bundler/gems/fluentd-793c9aa3a45b/
* ./opt/td-agent/lib/ruby/gems/2.7.0/gems/xxx

**Comment by kenhys** [comment]
Hmm, fluentd -c /etc/td-agent/td-agent.conf has been launched without bundle exec.

**Comment by ashie** [comment]
I'm considering 2 patterns

* Use released gem instead of using git source
* Create & add local gem repository to install built fluentd gem.

Procedure to realize later one:

```
$ mkdir -p repo/gems
$ cp /path/to/fluentd-x.y.z.gem repo/gems
$ cd repo && gem generate_index
```

Gemfile:
```
source "file:///path/to/repo" do
  gem "fluentd", "x.y.z"
end
```

**Comment by kenhys** [comment]
NOTE: need to add dependency to builder for gem generate_index.

**Comment by kenhys** [comment]
NOTE: not only BuildTask, UpdateLockfileTask also care to local gem repo.

**Comment by kenhys** [comment]
By enabling local gem repository

pros

* you can simplify Gemfile, set path to config.rb

```
source FLUENTD_LOCAL_GEM_REPO do
  gem "fluentd", FLUENTD_VERSION
end
```

cons:

* commit local gem repository in td-agent-builder
* Gemfile.lock contains specific local full path
