### ISSUE TITLE
Remove unnecessary perl depencencies in rpm packages

### ISSUE THREAD

**Issue by roicostas** [fluent-plugins-nursery/td-agent-builder#306]
Are perl dependencies really necessary for fluentd to work ?

When installing 4.1.1-1.el7 on rhel 7, it requires 27 perl packages that I think that may be unnecessary.

Checking yum/td-agent.spec.in history, I see that some work on that direction has been done for CentOS 6 in [5c90584](https://github.com/fluent-plugins-nursery/td-agent-builder/commit/5c905844edf9e4a2db556ef9ba16f4e3c4ea9c76). Could this be done for CentOS 7 too?

**Comment by kenhys** [comment]
Hmm,  surely these dependency is caused by:

```
# rpm -qp --requires td-agent-4.1.1-1.el7.x86_64.rpm |\grep perl
warning: td-agent-4.1.1-1.el7.x86_64.rpm: Header V4 RSA/SHA256 Signature, key ID ab97acbe: NOKEY
perl(Cwd)
perl(Getopt::Long)
perl(strict)
perl(warnings)
```

**Comment by kenhys** [comment]
I got it, this dependency is generated by bundled jeprof. (rpmbuild --rpmfcdebug indicates it)

```
 32 /root/rpmbuild/BUILDROOT/td-agent-4.1.1-1.el7.x86_64/opt/td-agent/bin/jeprof        Perl script, ASCII text executable [perl,script]
        R perl(Cwd)
        R perl(Getopt::Long)
        R perl(strict)
        R perl(warnings)
        R /usr/bin/env
```

**Comment by kenhys** [comment]
> Are perl dependencies really necessary for fluentd to work ?

So, not neccessary for fluentd itself but needed for bundled jeprof.

**Comment by kenhys** [comment]
@roicostas 
Anyway, thanks to the feedback!

**Comment by roicostas** [comment]
I see, so is it really necessary to package jeprof with fluentd ? 

I am not sure about it but it seems jeprof is a tool for "analyzing jemalloc's heap profile dumps" so i think that it could be installed later if needed if this allows to get rid of thoose dependencies.

I am not a sysadmin so I don't understand much about this, but when I asked to move to td-agent 4 they complained that now they have to maintain 1 new runtime (perl) and 27 new packages so it may be while until we can get upgraded to version 4 :(. I also understand that it may not be desireble in general in a production environment to install unnecessary dependencies.

Anyway thanks for the reply and the quick response!

**Comment by kenhys** [comment]
As only jeprof depends them, split it into td-agent-tools or something may be better. :thinking:

**Comment by ashie** [comment]
I'll remove jeprof from the package.
I reopen this for remind.
