### ISSUE TITLE
Vulnerability on nokogiri GHSA-7rrm-v45f-jp64

### ISSUE THREAD

**Issue by narwariyaazad** [fluent-plugins-nursery/td-agent-builder#324]
we are using nokogiri-1.11.1 version and this vulnerability is removed in >=1.11.4 version
this nokogiri package is coming from td-agent-gem list and i have also checked it in latest available version of td-agent(4.1.1)
but it is not resolved in this also.
Could you please provide detail of it .
CVE ID:- GHSA-7rrm-v45f-jp64
Thanks in advance.

**Comment by ashie** [comment]
https://github.com/fluent-plugins-nursery/td-agent-builder/issues/324

**Comment by kenhys** [comment]
Since td-agent 4.2.0, nokogiri 1.11.7 is used.
Please consider upgrading to latest td-agent.

https://github.com/fluent-plugins-nursery/td-agent-builder/blob/4c7486dee71d8eeaa98e56c774177842a66cbda4/td-agent/Gemfile.lock#L163
https://www.fluentd.org/blog/td-agent-v4.2.0-has-been-released
