### ISSUE TITLE
CI: Add tests for package installation

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#54]
ref: https://www.clear-code.com/blog/2020/5/5.html (written in Japanese)

**Comment by cosmo0920** [comment]
CentOS/Amazon Linux 2 and Debian GNU/Linux & Ubuntu installation testcases work is: #141

**Comment by cosmo0920** [comment]
Windows installation testcase work is #143.

**Comment by cosmo0920** [comment]
We'd completed to add installation testcases for supported platforms.
Closing.
