### ISSUE TITLE
Enable to build MSI package with any host OS

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#70]
Consider using windows-docker-machine :
https://github.com/StefanScherer/windows-docker-machine

**Comment by ashie** [comment]
Another choice to build MSI package with any Host OS: https://github.com/suchja/wix-toolset
It uses wine.

**Comment by kenhys** [comment]
No need to do.

**Comment by ashie** [comment]
ref: https://github.com/PietJankbal/Chocolatey-for-wine
