### ISSUE TITLE
Shouldn't use /opt directory

### ISSUE THREAD

**Issue by ashie** [fluent-plugins-nursery/td-agent-builder#9]
Since td-agent-builder is based on omnibu-td-agent, it installs most of files into /opt. But it's not recommended on Debian:

  * https://lintian.debian.org/tags/dir-or-file-in-opt.html

`dir-or-file-in-opt` errors can't be suppress by package's .lintian-overrides file.
Currently we suppress it forcedly by user's [lintian configuration](https://github.com/clear-code/td-agent-builder/tree/master/td-agent/debian/lintian/td-agent) because a lot of such errors make it hard that we find other errors or warnings, but it's not desired way.

We should consider put files into standard locations on GNU/Linux.

In addition, C:\opt isn't familiar on Windows.

**Comment by kenhys** [comment]
No plan to do.

**Comment by cosmo0920** [comment]
:ok_hand:
